Open tool file contents in rb
Fixes
https://sentry.galaxyproject.org/share/issue/7e108c13d6634c20bc885e3ec4a93ce8/:

```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8a in position 10: invalid start byte
  File "pulsar/managers/stateful.py", line 132, in _handling_of_preprocessing_state
    self._proxied_manager.launch(
  File "pulsar/managers/queued_drmaa.py", line 15, in launch
    self._check_execution_with_tool_file(job_id, command_line)
  File "pulsar/managers/base/directory.py", line 133, in _check_execution_with_tool_file
    self._check_execution(job_id, tool_id, command_line)
  File "pulsar/managers/base/__init__.py", line 189, in _check_execution
    contents = open(join(tool_files_dir, file)).read()
  File "<frozen codecs>", line 322, in decode
```
which is attempting to read PEHistogram.jar