Updated the job_conf_sample_remote_cluster.xml for the right default `destinations` id
In the `job_conf_sample_remote_cluster.xml`, the default destinations attribute was set on `drmaa` instead of `local_cluster`.

This was producing the following Exception:

```
Exception: Problem parsing the XML in file /Users/marenc01/Dev/galaxy/config/job_conf.xml, please correct the indicated portion of the file and restart Galaxy.<destinations> default attribute 'pulsar' does not match a defined id or tag in a child element
```

When launching Galaxy.